/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class suhu extends javax.swing.JFrame {

    /**
     * Creates new form suhu
     */
    public suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        r = new javax.swing.JTextField();
        c = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Konversi Suhu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 150, 40);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelvin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 260, 80, 20);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Celcius");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 60, 40);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fahrenheit");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 220, 90, 20);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reamur");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 90, 30);

        k.setEditable(false);
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });
        getContentPane().add(k);
        k.setBounds(150, 250, 110, 30);

        f.setEditable(false);
        getContentPane().add(f);
        f.setBounds(150, 210, 110, 30);

        r.setEditable(false);
        getContentPane().add(r);
        r.setBounds(150, 170, 110, 30);

        c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(140, 80, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Konversi Suhu"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 140, 260, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\suhu.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 190, 130, 190);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 320, 80, 30);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 380));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 420);

        setSize(new java.awt.Dimension(375, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        if(c.getSelectedItem().equals("1")){
            r.setText("0.8");
            f.setText("33.8");
            k.setText("274");
        }
        else
        if(c.getSelectedItem().equals("2")){
            r.setText("1.6");
            f.setText("35.6");
            k.setText("275");
        }
        else
        if(c.getSelectedItem().equals("3")){
            r.setText("2.4");
            f.setText("37.4");
            k.setText("276");
        }
        else
        if(c.getSelectedItem().equals("4")){
            r.setText("3.2");
            f.setText("39.2");
            k.setText("277");
        }
        else
        if(c.getSelectedItem().equals("5")){
            r.setText("4.0");
            f.setText("41.0");
            k.setText("278");
        }
        else
        if(c.getSelectedItem().equals("6")){
            r.setText("4.8");
            f.setText("42.8");
            k.setText("279");
        }
        else
        if(c.getSelectedItem().equals("7")){
            r.setText("5.6");
            f.setText("44.6");
            k.setText("280");
        }
        else
        if(c.getSelectedItem().equals("8")){
            r.setText("6.4");
            f.setText("46.4");
            k.setText("281");
        }
        else
        if(c.getSelectedItem().equals("9")){
            r.setText("7.2");
            f.setText("48.2");
            k.setText("282");
        }
        else
        if(c.getSelectedItem().equals("10")){
            r.setText("8.0");
            f.setText("50.0");
            k.setText("283");
        }
        else
        if(c.getSelectedItem().equals("11")){
            r.setText("8.8");
            f.setText("51.8");
            k.setText("284");
        }
        else
        if(c.getSelectedItem().equals("12")){
            r.setText("9.6");
            f.setText("53.6");
            k.setText("285");
        }
        else
        if(c.getSelectedItem().equals("13")){
            r.setText("10.4");
            f.setText("55.4");
            k.setText("286");
        }
        else
        if(c.getSelectedItem().equals("14")){
            r.setText("11.2");
            f.setText("57.2");
            k.setText("287");
        }
        else
        if(c.getSelectedItem().equals("15")){
            r.setText("12.0");
            f.setText("59.0");
            k.setText("288");
        }
        else
        if(c.getSelectedItem().equals("16")){
            r.setText("12.8");
            f.setText("60.8");
            k.setText("289");
        }
        else
        if(c.getSelectedItem().equals("17")){
            r.setText("14.6");
            f.setText("62.6");
            k.setText("290");
        }
        else
        if(c.getSelectedItem().equals("18")){
            r.setText("14.4");
            f.setText("64.4");
            k.setText("291");
        }
        else
        if(c.getSelectedItem().equals("19")){
            r.setText("15.2");
            f.setText("66.2");
            k.setText("292");
        }
        else
        if(c.getSelectedItem().equals("20")){
            r.setText("16.0");
            f.setText("68.0");
            k.setText("293");
        }
        else
        if(c.getSelectedItem().equals("21")){
            r.setText("16.8");
            f.setText("69.8");
            k.setText("294");
        }
        else
        if(c.getSelectedItem().equals("22")){
            r.setText("17.6");
            f.setText("71.6");
            k.setText("295");
        }
        else
        if(c.getSelectedItem().equals("23")){
            r.setText("18.4");
            f.setText("73.4");
            k.setText("296");
        }
        else
        if(c.getSelectedItem().equals("24")){
            r.setText("19.2");
            f.setText("75.2");
            k.setText("297");
        }
        else
        if(c.getSelectedItem().equals("25")){
            r.setText("20.0");
            f.setText("77.0");
            k.setText("298");
        }
        else
        if(c.getSelectedItem().equals("26")){
            r.setText("20.8");
            f.setText("78.8");
            k.setText("299");
        }
        else
        if(c.getSelectedItem().equals("27")){
            r.setText("21.6");
            f.setText("80.6");
            k.setText("300");
        }
        else
        if(c.getSelectedItem().equals("28")){
            r.setText("22.4");
            f.setText("82.4");
            k.setText("301");
        }
        else
        if(c.getSelectedItem().equals("29")){
            r.setText("23.2");
            f.setText("84.2");
            k.setText("302");
        }
        else
        if(c.getSelectedItem().equals("30")){
            r.setText("24.0");
            f.setText("86.0");
            k.setText("303");
        }
        else
        if(c.getSelectedItem().equals("31")){
            r.setText("24.8");
            f.setText("87.8");
            k.setText("304");
        }
        else
        if(c.getSelectedItem().equals("32")){
            r.setText("25.6");
            f.setText("89.6");
            k.setText("305");
        }
        else
        if(c.getSelectedItem().equals("33")){
            r.setText("26.4");
            f.setText("91.4");
            k.setText("306");
        }
        else
        if(c.getSelectedItem().equals("34")){
            r.setText("27.2");
            f.setText("93.2");
            k.setText("307");
        }
        else
        if(c.getSelectedItem().equals("35")){
            r.setText("28.0");
            f.setText("95.0");
            k.setText("308");
        }
        else
        if(c.getSelectedItem().equals("36")){
            r.setText("28.8");
            f.setText("96.8");
            k.setText("309");
        }
        else
        if(c.getSelectedItem().equals("37")){
            r.setText("29.6");
            f.setText("98.6");
            k.setText("310");
        }
        else
        if(c.getSelectedItem().equals("38")){
            r.setText("30.4");
            f.setText("100.4");
            k.setText("311");
        }
        else
        if(c.getSelectedItem().equals("39")){
            r.setText("31.2");
            f.setText("102.2");
            k.setText("312");
        }
        else
        if(c.getSelectedItem().equals("40")){
            r.setText("32.0");
            f.setText("104.0");
            k.setText("313");
        }
        else
        if(c.getSelectedItem().equals("41")){
            r.setText("32.8");
            f.setText("105.8");
            k.setText("314");
        }
        else
        if(c.getSelectedItem().equals("42")){
            r.setText("33.6");
            f.setText("107.6");
            k.setText("315");
        }
        else
        if(c.getSelectedItem().equals("43")){
            r.setText("34.4");
            f.setText("109.4");
            k.setText("316");
        }
        else
        if(c.getSelectedItem().equals("44")){
            r.setText("35.2");
            f.setText("111.2");
            k.setText("317");
        }
        else
        if(c.getSelectedItem().equals("45")){
            r.setText("36.0");
            f.setText("113.0");
            k.setText("318");
        }
        else
        if(c.getSelectedItem().equals("46")){
            r.setText("36.8");
            f.setText("114.8");
            k.setText("319");
        }
        else
        if(c.getSelectedItem().equals("47")){
            r.setText("37.6");
            f.setText("116.6");
            k.setText("320");
        }
        else
        if(c.getSelectedItem().equals("48")){
            r.setText("38.4");
            f.setText("118.4");
            k.setText("321");
        }
        else
        if(c.getSelectedItem().equals("49")){
            r.setText("39.2");
            f.setText("120.2");
            k.setText("322");
        }
        else
        if(c.getSelectedItem().equals("50")){
            r.setText("40.0");
            f.setText("122.0");
            k.setText("323");
        }
        else
        if(c.getSelectedItem().equals("51")){
            r.setText("40.8");
            f.setText("123.8");
            k.setText("324");
        }
        else
        if(c.getSelectedItem().equals("52")){
            r.setText("41.6");
            f.setText("125.6");
            k.setText("325");
        }
        else
        if(c.getSelectedItem().equals("53")){
            r.setText("42.4");
            f.setText("127.4");
            k.setText("326");
        }
        else
        if(c.getSelectedItem().equals("54")){
            r.setText("43.2");
            f.setText("129.2");
            k.setText("327");
        }
        else
        if(c.getSelectedItem().equals("55")){
            r.setText("44.0");
            f.setText("131.0");
            k.setText("328");
        }
        else
        if(c.getSelectedItem().equals("56")){
            r.setText("44.8");
            f.setText("132.8");
            k.setText("329");
        }
        else
        if(c.getSelectedItem().equals("57")){
            r.setText("45.6");
            f.setText("134.6");
            k.setText("330");
        }
        else
        if(c.getSelectedItem().equals("58")){
            r.setText("46.4");
            f.setText("136.4");
            k.setText("331");
        }
        else
        if(c.getSelectedItem().equals("59")){
            r.setText("47.2");
            f.setText("138.2");
            k.setText("332");
        }
        else
        if(c.getSelectedItem().equals("60")){
            r.setText("48.0");
            f.setText("140.0");
            k.setText("333");
        }
        else
        if(c.getSelectedItem().equals("61")){
            r.setText("48.8");
            f.setText("141.8");
            k.setText("334");
        }
        else
        if(c.getSelectedItem().equals("62")){
            r.setText("49.6");
            f.setText("143.6");
            k.setText("335");
        }
        else
        if(c.getSelectedItem().equals("63")){
            r.setText("50.4");
            f.setText("145.4");
            k.setText("336");
        }
        else
        if(c.getSelectedItem().equals("64")){
            r.setText("51.2");
            f.setText("147.2");
            k.setText("337");
        }
        else
        if(c.getSelectedItem().equals("65")){
            r.setText("52.0");
            f.setText("149.0");
            k.setText("338");
        }
        else
        if(c.getSelectedItem().equals("66")){
            r.setText("52.8");
            f.setText("150.8");
            k.setText("339");
        }
        else
        if(c.getSelectedItem().equals("67")){
            r.setText("53.6");
            f.setText("152.6");
            k.setText("340");
        }
        else
        if(c.getSelectedItem().equals("68")){
            r.setText("54.4");
            f.setText("154.4");
            k.setText("341");
        }
        else
        if(c.getSelectedItem().equals("69")){
            r.setText("55.2");
            f.setText("156.2");
            k.setText("342");
        }
        else
        if(c.getSelectedItem().equals("70")){
            r.setText("56.0");
            f.setText("158.0");
            k.setText("343");
        }
        else
        if(c.getSelectedItem().equals("71")){
            r.setText("56.8");
            f.setText("159.8");
            k.setText("344");
        }
        else
        if(c.getSelectedItem().equals("72")){
            r.setText("57.6");
            f.setText("161.6");
            k.setText("345");
        }
        else
        if(c.getSelectedItem().equals("73")){
            r.setText("58.4");
            f.setText("163.4");
            k.setText("346");
        }
        else
        if(c.getSelectedItem().equals("74")){
            r.setText("59.2");
            f.setText("165.2");
            k.setText("347");
        }
        else
        if(c.getSelectedItem().equals("75")){
            r.setText("60.0");
            f.setText("167.0");
            k.setText("348");
        }
        else
        if(c.getSelectedItem().equals("76")){
            r.setText("60.8");
            f.setText("168.8");
            k.setText("349");
        }
        else
        if(c.getSelectedItem().equals("77")){
            r.setText("61.6");
            f.setText("170.6");
            k.setText("350");
        }
        else
        if(c.getSelectedItem().equals("78")){
            r.setText("62.4");
            f.setText("172.4");
            k.setText("351");
        }
        else
        if(c.getSelectedItem().equals("79")){
            r.setText("63.2");
            f.setText("174.2");
            k.setText("352");
        }
        else
        if(c.getSelectedItem().equals("80")){
            r.setText("64.0");
            f.setText("176.0");
            k.setText("353");
        }
        else
        if(c.getSelectedItem().equals("81")){
            r.setText("64.8");
            f.setText("177.8");
            k.setText("354");
        }
        else
        if(c.getSelectedItem().equals("82")){
            r.setText("65.6");
            f.setText("179.6");
            k.setText("355");
        }
        else
        if(c.getSelectedItem().equals("83")){
            r.setText("66.4");
            f.setText("181.4");
            k.setText("356");
        }
        else
        if(c.getSelectedItem().equals("84")){
            r.setText("67.2");
            f.setText("183.2");
            k.setText("357");
        }
        else
        if(c.getSelectedItem().equals("85")){
            r.setText("68.0");
            f.setText("185.0");
            k.setText("358");
        }
        else
        if(c.getSelectedItem().equals("86")){
            r.setText("68.8");
            f.setText("186.8");
            k.setText("359");
        }
        else
        if(c.getSelectedItem().equals("87")){
            r.setText("69.6");
            f.setText("188.6");
            k.setText("360");
        }
        else
        if(c.getSelectedItem().equals("88")){
            r.setText("70.4");
            f.setText("190.4");
            k.setText("361");
        }
        else
        if(c.getSelectedItem().equals("89")){
            r.setText("71.2");
            f.setText("192.2");
            k.setText("362");
        }
        else
        if(c.getSelectedItem().equals("90")){
            r.setText("72.0");
            f.setText("194.0");
            k.setText("363");
        }
        else
        if(c.getSelectedItem().equals("91")){
            r.setText("72.8");
            f.setText("195.8");
            k.setText("364");
        }
        else
        if(c.getSelectedItem().equals("92")){
            r.setText("73.6");
            f.setText("197.6");
            k.setText("365");
        }
        else
        if(c.getSelectedItem().equals("93")){
            r.setText("74.4");
            f.setText("199.4");
            k.setText("366");
        }
        else
        if(c.getSelectedItem().equals("94")){
            r.setText("75.2");
            f.setText("201.2");
            k.setText("367");
        }
        else
        if(c.getSelectedItem().equals("95")){
            r.setText("76.0");
            f.setText("203.0");
            k.setText("368");
        }
        else
        if(c.getSelectedItem().equals("96")){
            r.setText("76.8");
            f.setText("204.8");
            k.setText("369");
        }
        else
        if(c.getSelectedItem().equals("97")){
            r.setText("77.6");
            f.setText("206.6");
            k.setText("370");
        }
        else
        if(c.getSelectedItem().equals("98")){
            r.setText("78.4");
            f.setText("208.4");
            k.setText("371");
        }
        else
        if(c.getSelectedItem().equals("99")){
            r.setText("79.2");
            f.setText("210.2");
            k.setText("372");
        }
        else
        if(c.getSelectedItem().equals("100")){
            r.setText("80.0");
            f.setText("212.0");
            k.setText("373");
        }
    }//GEN-LAST:event_cActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        r.setText("");
        f.setText("");
        k.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField k;
    private javax.swing.JTextField r;
    // End of variables declaration//GEN-END:variables
}
